secret_key = ""
allowed_hosts = [
    "hawk.carrade.eu"
]

contents_dir = "/home/hawk/data"
logs_dir = "/var/log/hawk"

sentry_dsn = ""

[databases.default]
host = ""
port = ""
name = ""
user = ""
password = ""
