# Generated by Django 2.2.4 on 2019-08-31 17:58

from django.db import migrations, models
import hawk_gui.models


# fmt: off
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published at')),
                ('published_by', models.GenericIPAddressField(blank=True, null=True, verbose_name='Published by')),
                ('minecraft_version', models.CharField(db_index=True, max_length=64, verbose_name='Minecraft version')),
                ('generator_name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Generator')),
                ('generator_link', models.URLField(blank=True, null=True, verbose_name='Generator link')),
                ('views_count', models.IntegerField(default=0, verbose_name='Views count')),
                ('raw_report', models.FileField(upload_to=hawk_gui.models.raw_report_location, verbose_name='Raw report')),
                ('processed_report', models.FileField(upload_to=hawk_gui.models.processed_report_location, verbose_name='Processed report')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-published_at'],
            },
        ),
    ]
