# Generated by Django 2.2.4 on 2019-08-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hawk_gui", "0002_add_uuid_field_to_report")]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="minecraft_version",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Minecraft version",
            ),
        )
    ]
