# Generated by Django 2.2.5 on 2019-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hawk_gui", "0004_non_editable_report_fields")]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "report",
                "verbose_name_plural": "reports",
            },
        ),
        migrations.AlterField(
            model_name="report",
            name="slug",
            field=models.SlugField(max_length=8, verbose_name="Slug"),
        ),
    ]
