# Generated by Django 2.2.5 on 2019-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hawk_gui", "0005_slugs_are_height_char_long")]

    operations = [
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(
                default="", editable=False, max_length=256, verbose_name="Title"
            ),
            preserve_default=False,
        )
    ]
