# Generated by Django 3.2 on 2021-04-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_gui', '0006_store_title_in_report_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(max_length=8, unique=True, verbose_name='Slug'),
        ),
    ]
