# Generated by Django 3.2 on 2021-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hawk_gui', '0007_add_index_to_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='Slug'),
        ),
    ]
