name: CI – CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: ["test"]

    # only for commits to the master branch
    if: "github.ref == 'refs/heads/master'"

    steps:
      - name: Checkout Ansible
        uses: actions/checkout@v2
        with:
          repository: "zDevelopers/HawkGUI-Ansible"
      - name: Write the SSH key to file
        run: 'echo "$SSH_KEY" > id_rsa'
        shell: bash
        env:
          SSH_KEY: ${{ HAWK_SSH_KEY }}
      - name: Write Ansible Vault password to file
        run: 'echo "$VAULT_PASS" > vault_password'
        shell: bash
        env:
          VAULT_PASS: ${{ HAWK_ANSIBLE_VAULT_PASSWORD }}
      - name: Run Ansible playbook to deploy to production
        run: |
          ansible-playbook --vault-password-file vault_password --private-key id_rsa playbook.yml
